name = "HH Server Client"
author = "My_name_is_Lee"
version = "BE1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2df919e80d5e15b3d27e8546ebf83f69f5a9a3f946890c7d4f1dee72de8af40f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
