name = "HH Server Client"
author = "My_name_is_Lee"
version = "BE1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "613cdc2c759bae652ec1aaed0d16d1881c73845ff3636535deb72893a7375fbf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.196"

[options]
datapack-folder = "config/openloader/pack/"
