name = "HH Server Client"
author = "My_name_is_Lee"
version = "BE1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "797bd104a4d3095c527bda4a91789f2b9f62c50ddf8a428b3237a0e514704afe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
