name = "HH Server Client"
author = "My_name_is_Lee"
version = "BE1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaa1ee7e01ad6d1f987dc56b32f1efd0378203eb7fbdd0cc79284d0ae9fc9ff9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
