name = "HH Server Client"
author = "My_name_is_Lee"
version = "BE1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cb822c9e950e28bbcc1f3ebb17956700690088b87c79d9e1da6da73cda8ec97"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.196"

[options]
datapack-folder = "config/openloader/pack/"
