name = "HH Server Client"
author = "My_name_is_Lee"
version = "BE1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8d98b399f27dcf17df22d3e40d4f2eed7044109cb91ba242b399e1db1ddb3cc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
